title: "NonZero Venture Capital"
tagline: "Seeking Non-Zero Chances"
description: "A Binary Venture Capital Firm"
#github_username: nonzerovc@protonmail.com 
baseurl: "/"
url: "https://nonzerovc.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  #- preview.md
  #- read-me.md
  

# set the size of the text to 'large' or 'small', default is small
font-size: large
