title: "NonZero Venture Capital"
tagline: "Seeking NonZero Chances"
description: "A Binary Venture Capital Firm"
github_username: nonzerovc
baseurl: "/"
url: "https://nonzerovc.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
